- hosts: all
  tasks:
    # - apt: package=vim state=present
    - git: repo="https://github.com/lpenz/dotvim.git" dest="{{lookup('env','HOME')}}/.vim"
    - file: state=link src="{{lookup('env','HOME')}}/.vim/vimrc" dest="{{lookup('env','HOME')}}/.vimrc"
    - file: state=link src="{{lookup('env','HOME')}}/.vim/gvimrc" dest="{{lookup('env','HOME')}}/.gvimrc"
    - command: vim -X -n -u NONE -c 'silent! source ~/.vimrc' -c 'PlugInstall' -c 'qa!'
